### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ChefZander** [srounet/Pymem#54]
Im having a problem. I wrote a tool with pymem so i can do
`inject.pyc <process> <python script file>`
the problem is: i can only inject into python related processes: normal python files, pyc files, even auto-py-to-exe compiled python-exe files, but just not for example custom C++ programs by me. 
Error messge:
![grafik](https://user-images.githubusercontent.com/60350322/116078173-93ce2d00-a696-11eb-8df1-f9475dcb5343.png)

Is it just a mistake my me?

Thanks!

Edit 1: I forgot to mention, i CAN inject into notepad, maybe other applets too but i didnt test

**Comment by srounet** [comment]
Please use the Issue template that was provided when you created the issue, it's there for a reason.

**Describe the bug**
A clear and concise description of what the bug is.

**Your Environment**

1. python version (3.6, 3.8...)
2. os version (32/64)
3. pymem version

**Expected behavior**
A clear and concise description of what you expected to happen.

**Traceback**
If applicable, add tracebacks to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by ChefZander** [comment]
I fixed it, just update python to v3.9.4 and set a flag in the antivirus
